<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Ana.DataLayer</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="AWSSDK.DynamoDBv2" Version="4.0.21.6" />
    </ItemGroup>

</Project>
